export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const SELECT_CONVERSATION = "SELECT_CONVERSATION";
export const GET_MESSAGES = "GET_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const CREATE_NEW_CONVERSATION = "CREATE_NEW_CONVERSATION";
